### ISSUE TITLE
Backlash at EOL not handled correctly

### ISSUE THREAD

**Issue by The-Compiler** [markw65/monkeyc-optimizer#1]
Hey! I'm hoping this is the right place to report this - I'm seeing this in the "Prettier Monkey C" extension if I run "Build optimized project", but I'm assuming the issue is in this project.

Monkey C source code such as:

```
        var test = "foo" + \
            "bar";
```

builds fine with Monkey C, but the extension claims:

```
Expected "!", "(", "+", "-", ":", "[", "me", "self", "{", "~", comment, end of line, identifier, number, string, or whitespace but "\\" found.
```

**Comment by markw65** [comment]
It's actually [prettier-plugin-monkeyc](https://github.com/markw65/prettier-plugin-monkeyc) that does the parsing for this project, and for [prettier-extension-monkeyc](https://github.com/markw65/prettier-extension-monkeyc), but reporting bugs against any of them is fine.

btw do you know of any documentation for this feature? I assume its analogous to \ in "C", but hadn't come across it in MonkeyC.

In any case, I'll try to get a fix out later today.

**Comment by The-Compiler** [comment]
Hmm, you're right - I'd expect it to be documented [somewhere around here](https://developer.garmin.com/connect-iq/monkey-c/functions/), but indeed it is not.

I used it to build up a rather long string, and didn't really think about it - like you say, I'd expect it to work the same as in other languages. Thanks for the fix, no hurry!

**Comment by markw65** [comment]
Ok, it turns out to be hard to reverse engineer.

How exactly did you use it to build a long string? Your example doesn't need the `\` at all... this works exactly the same:

```
var test = "foo" +
            "bar";
```

Backslash *doesn't* seem to work like in C at all:

```
  var x = "Foo\
bar";
```

In C, the back-slash new-line sequence would be removed, and the string would be "Foobar", but this is a syntax error in MonkeyC.

```
// a single-line comment split \
accross two lines
```

In C or C++ this would be joined into a single line, and then the comment would be removed. In MonkeyC that doesn't happen, and "across two lines" is reported as a syntax error.

I can't really figure out what it *does* do; it seems to simply swallow the following character in a lot of cases; but not *all* cases.

```
  var x.= "foo" + \ "bar"; // seems to be ignored
  var y = "foo" + \"bar"; // syntax error
  var z = "foo" + \""bar"; // the \" is just ignored
  var w = \0; // crashes the MonkeyC compiler
  {
    var v = 42;
    return \v; // same as "return;"
  }
  {
    var v = 42;
    return \yv; // same as "return x;"
  }
```

So I'm currently not sure what to do with this... its undocumented, doesn't seem to do anything useful, and isn't consistent enough to make it easy to emulate.

If you *have* a use case, can you let me know exactly what it is? The example you've provided so far works perfectly well without the `\`, so it seems like it would be better to just avoid using it.

**Comment by The-Compiler** [comment]
Oh! Indeed my code works fine without those backslashes, that's just something I've never considered.

Given that it's undocumented and apparently not very obvious how it works, let's close this. Thanks for having a look! I found another unexpected syntax error, I'll open a separate issue in the prettier-plugin-monkeyc repo for that.

**Comment by The-Compiler** [comment]
...eh, nevermind about the other one actually. That was me using e.g. `data as String | Dictionary | Null` for monkey types, when I should be using `or` in place of `|`. Guess that's just me being used to Python, as it seems to work, but also isn't documented or used by Garmin anywhere as far as I can see.

**Comment by markw65** [comment]
I ended up "fixing" this, at least to the extent that now `\<letter>`, `\"`, and `\<space>` are all treated as whitespace, if they occur where whitespace is valid.

I also fixed the `or` vs `|` issue so the parser now accepts `|`, and the formatter will convert `|` to `or`
