### ISSUE TITLE
Activity.Info.timerTime hint shows info about altitude

### ISSUE THREAD

**Issue by flocsy** [markw65/monkeyc-optimizer#16]
Probably this is a bug in the Garmin documentation html, but maybe it's something you can improve:

Why I have a variable that is info as Activity.Info, then if stop the mouse over info.timerTime then I see this:
![Screenshot 2024-03-24 at 12 53 37](https://github.com/markw65/monkeyc-optimizer/assets/953924/f8447192-ef88-4dca-ac9e-a88eb5e165b9)

it looks like the 1st line (which took me some time to realize that it's there...) is indeed about timerTime, but all the rest is about the next entry in the html.

**Comment by markw65** [comment]
It's inconsistencies in the layout of different kinds of objects. 

For instance methods, there's an anchor `<method-name>-instance_function`, but if you just include the element with the anchor, all you get is the signature. So my code fetches the element, finds its parent, and returns that.

It turns out that for instance variables, there's an anchor `<variable-name>-var`, and that includes everything about the variable. And in this case the parent is the entire section containing all the instance variables.

Its an easy fix - just one more check.

**Comment by markw65** [comment]
The fix for this one is going to be in https://github.com/markw65/prettier-extension-monkeyc by the way

**Comment by markw65** [comment]
Fixed by https://github.com/markw65/prettier-extension-monkeyc/commit/e8be804cd5f4e4e1707466e0f82cda5132a9af58
