### ISSUE TITLE
Build failed due to hidden member access from another class with strict type check enabled

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#29]
I'm not sure, but I think I saw this problem earlier, but now it can be reproduced only with `"prettierMonkeyC.typeCheckLevel": "Strict"`.

Original code:
```monkey-c
import Toybox.Lang;

class Test1 {
    hidden static const SIZE = [].size();

    static function getSize() as Number {
        return SIZE;
    }
}

class Test2 {
    hidden var value as Number;

    function initialize() {
        value = Test1.getSize();
    }
}
```

Optimized:
```monkey-c
import Toybox.Lang;

class Test1 {
    hidden static const SIZE = [].size();
}

class Test2 {
    hidden var value as Number;

    function initialize() {
        // Cannot find symbol ':SIZE' on class definition '$.Test1'.
        value = Test1.SIZE;
    }
}
```

Probably, `hidden` modifier should be replaced with `public` in `const` declaration during optimization or methods like `getSize()` should be kept. Personally, I'd prefer to change the modifier.

**Comment by markw65** [comment]
> Personally, I'd prefer to change the modifier

For now I've gone with disabling the inlining. Dropping the modifier can have subtle effects on the meaning of the program (at least, thats definitely the case for `private`, I'm not sure about `hidden`), and I'm not doing the necessary analysis to determine whether that's the case here.

**Comment by markw65** [comment]
@m4tiz5zktonj 

Yes, I did see it, but I've been a bit swamped due to [Garmin's store suddenly rejecting apps built with the post build optimizer enabled](https://forums.garmin.com/developer/connect-iq/f/discussion/371201/app-updates-blocked-due-to-security-threat) - now resolved.

I agree this is incorrect, and it would be nice to refuse to inline and provide a warning that explains why. But this seems very low priority to me. There is no way to correctly inline this (I could change it to not be private, of course, but that can have subtle consequences - so there would be cases where it would be wrong to do that - and I don't want to go down that path right now), so at best you would get a warning, and no inlining.

So for now I consider this "user error", and the fix is to not specify `(:inline)`.

>         //  '5 +' is no more, though it won't affect anything, at least in this particular case

This is intentional. Garmin's parser rejects statements like `5+foo();`, so the optimizer has to clean up unused operations like this.

But if you can find a case where it drops the `5+` where it matters that's a bug...
