### ISSUE TITLE
problems with personality path

### ISSUE THREAD

**Issue by flocsy** [markw65/monkeyc-optimizer#32]
WARNING: release.jungle:6: Personality path '/Users/me/garmin/Foo/lang/heb/bin/optimized/../../../../../../../Library/ApplicationSupport/Garmin/ConnectIQ/Devices/fr255' cannot be resolved to a valid path.

For some reason the space is missing in: "Application Support"

line 6 is:

fr255.personality = ../../../../../../../Library/Application Support/Garmin/ConnectIQ/Devices/fr255
So I guess you'll need to add quotes, at least when there's a space in there
I'll add that this doesn't happen when I do a "regular" build in /Users/me/garmin/Foo/, only when I build in /Users/me/garmin/Foo/lang/heb/ which is a generated directory with a generated monkey.jungle and manifest.xml, however it does work without the optimizer, so there's no reason it shouldn't work with it as well.

Line 6 looks line this in the "regular" build:
fr255.personality = ../../resources

So it is possible there are 2 bugs: 1. non-escaped space, and 2. I wonder why the ../../personality was replaced by the default device folder in the "generated" build. BTW my original monkey.jungle doesn't include the word personality in neither build. (Well it does, but only as an excludeAnnotation).

**Comment by markw65** [comment]
When I was fixing #27 I had a vague suspicion that I should quote that path - but I tried it and to my surprise it worked, so I moved on.

As I was reading this, it hit me. I type that path so often that a long time ago I added an alias: `ApplicationSupport -> Application\ Support` just to make typing and completion easier.

And then, without quotes, Garmin's jungle parser reads a list of white space separated words, and joins them together with no intervening space.

So

base.sourcePath = s o ur ce

is equivalent to

base.sourcePath = source

So it really does work on my mac, but not on anybody else's (unless they add the same sym link)!

Will fix asap

**Comment by markw65** [comment]
> I wonder why the ../../personality was replaced by the default device folder

It's because it's there in the default jungle (look at sdk-path/bin/default.jungle). I *could* pick it up by doing

fr255.personality = $(fr255.personality);<whatever-else>

And in fact, I used to do that for the resource paths etc. But that risks picking up paths that the user explicitly didn't want (and there were bugs because of it). So now I try to figure out all the paths that should be there, and add them (and failing to add the device personality path is what caused #27).

**Comment by markw65** [comment]
One other question. In the forum you wrote

```
fr255.personality = ../../../../../../../Library/Application Support/Garmin/ConnectIQ/Devices/fr255
So I guess you'll need to add quotes, at least when there's a space in there
I'll add that this doesn't happen when I do a "regular" build in /Users/me/garmin/Foo/, only when I build in /Users/me/garmin/Foo/lang/heb/ which is a generated directory with a generated monkey.jungle and manifest.xml, however it does work without the optimizer, so there's no reason it shouldn't work with it as well.

Line 6 looks line this in the "regular" build:
fr255.personality = ../../resources
```

(I'm copying here because that thread is so noisy right now any responses will get lost)

If I understand correctly, the failing case has a generated monkey.jungle, probably in a subdirectory relative to the original monkey.jungle? If so, did you also put a generated manifest.xml next to it, or does the generated jungle refer to the original, in the original directory?

I'm trying to understand why the non-generated one has ../../resources, while the generated one does not. Not being there means that my optimizer didn't find a directory named "resources". The rules for finding relative paths are that paths in a jungle file are relative to that jungle file; but paths in default.jungle are relative to manifest.xml. So if both jungle files share the same manifest.xml, I would expect that either both find resources, or both fail to find it. Otoh, if you also generated manifest.xml, it's quite likely that it wouldn't find it.

Some details of the layout of the project - specifically where the manifest, and jungle files are, and where any "resources" directories are, for the original, and generated projects could help clear things up.

**Comment by flocsy** [comment]
Exactly, both the monkey.jungle and the manifest.xml are generated and put into /lang/<lang>/. Manifest has a separate id generated for each language. And monkey.jungle references mainly ../../<whatever: source, resources, resources-<lang>, gen/lang/<lang>, features/...>  (though also a bit in source/ (which means it's /lang/<lang>/source/ relative to the root)

I think for the sake of reproducing it it's enough to set up any project, then add lang/eng/ and copy the manifest to there and create a monkey.jungle that adds ../../ before every path of the original. 

When I work on the language versions, then I have a new window of VSC open with /lang/<lang>/ as "root", and both VSC and the optimizer worked OK until last week.

It is possible that fixing the unquoted space will fix the other problem too.

**Comment by flocsy** [comment]
Hi, 2.0.88 dd fix the space, but the other issue still persists. I opened a new issue for it: https://github.com/markw65/monkeyc-optimizer/issues/34
