### ISSUE TITLE
Tuples related issues with strict type check enabled

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#38]
Original code:
```monkey-c
import Toybox.Lang;
import Toybox.System;

class Test {
    var array as Array<Number>;
    var value as Number;

    function initialize() {
        array = getArray([0]);
        value = getTuple(0)[0];

        System.println(array);
        System.println(value);
    }

    function getArray(values as Array<Number>) as Array<Number> {
        var result = [];

        // Argument 1 to $.Toybox.Lang.Array.addAll expected to be Array<Never> but got Array<Number>
        result.addAll(values);

        return result;
    }

    function getTuple(value as Number) as [Number, Float] {
        return [value, value.toFloat()];
    }
}
```

Optimized:
```monkey-c
import Toybox.Lang;
import Toybox.System;

class Test {
    var array as Array<Number>;
    var value as Number;

    function initialize() {
        var pre_0;
        pre_0 = 0;
        array = getArray([pre_0]);
        // Assigned value type 'PolyType<$.Toybox.Lang.Float or $.Toybox.Lang.Number>' to member '$.Test.value' of non-poly type '$.Toybox.Lang.Number'.
        value = getTuple(pre_0)[pre_0];

        System.println(array);
        System.println(value);
    }

    function getArray(values as Array<Number>) as Array<Number> {
        var result = [];

        // Argument 1 to $.Toybox.Lang.Array.addAll expected to be Array<Never> but got Array<Number>
        result.addAll(values);

        return result;
    }

    function getTuple(value as Number) as [Number, Float] {
        return [value, value.toFloat()];
    }
}
```

**Comment by markw65** [comment]
One problem here is that Garmin's type checker is particularly unsound wrt tuples. I've filed a number of bug reports.

I've intentionally made my type checker stricter. So for example, `[]` has the type Array<Never>; which means that `result`'s type is the same, and you can only add elements of type Never to it (which obviously dont' exist).

You can make both type checkers happy by writing

```
var result = [] as Array<Number>;
```

I just did some experiments, and several of the cases I was concerned about with Garmin's type checker have now been fixed. It seems to special case an empty array as Array<Any>. That doesn't seem too unreasonable - but I need to think it through...

For the other issue, I guess Garmin's type checker can handle extracting an element of a tuple via a literal, but if you try to extract an element via a variable that was set to a literal, it can't tell which element is being extracted. I'm unwilling to put in the effort to figure out contexts where Garmin's compiler can't handle a variable-whose-value-is-a-known-literal, but can handle the literal - but I guess a solution here is to add an option to not apply size-based-pre to literals. Since the post build optimizer generally does a better job of that anyway, it would make sense.

And again. you can work around this with a cast:

```
        value = getTuple(0)[0] as Number;
```
And yes, that loses some of the appeal of tuples. Or you could turn off (or turn down) garmin's type checker in the optimized build...

**Comment by markw65** [comment]
For now, I've decided to match Garmin's behavior on array.add() and array.addAll, so your example will work.

The rule seems to be
 - if `a` has type `Array<T>` then `a.add(x)` requires that `x` be a subtype of `T`, and `a.addAll(x)` requires that `x` be a subtype of `Array<T>`.
 - if `a` has tuple type, then `a.add(x)` can add anything, and the result is a tuple with one extra element, and `a.addAll(x)` can also add anything, resulting in a tuple if `x` is a tuple, or `Array<U>` where `U` is the union of the types already in `a`, and the types in `x`.

I don't really like this. Consider:

```
function foo(a as [Number, Number]) as Void {
  a.addAll(["hello", "world"]);
}
function bar() as [Number, Number] {
  var a = [1,2];
  foo(a);
  return a;
}
```

Garmin's compiler (and my type checker) assumes that `a` is still a `[Number, Number]` after the call to foo, but it's not.

The only safe thing to do seems to be to disallow `add` and `addAll` on tuple types.
