### ISSUE TITLE
"Redefinition of <barrel class>". Previous definition at ".../bin/optimized/raw-barrels/..."

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#42]
Steps to reproduce:
1. Generate barrel with the following content:
```monkey-c
module TestBarrel {
    class BarrelClass {
        function barrelMethod() as Void {}
    }
}
```
2. Build barrel.
3. Generate simple non-barrel app.
4. Open app and add dependency to the barrel as compiled ".barrel" file dependency.
5. Try to build app.

```
ERROR: ... /tmp/TestBarrel-0.0.0.barrel.../content/TestBarrel.mc:2: Redefinition of '$.TestBarrel.BarrelClass'. Previous definition at .../bin/optimized/raw-barrels/TestBarrel-0.0.0-.../content/TestBarrel.mc:2.
```

Error can be avoided by adding the following code to app's `monkey.jungle`:
```
base.sourcePath = source/**.mc
```

**Comment by markw65** [comment]
This isn't really specific to barrels. The optimizer has to put its files somewhere, and the default is under `bin`. If you've configured your monkey.jungle to look for source files in the bin directory (which unfortunately is the default), then `Monkey C: Build Project` will fail.

The only difference here is that in order to analyze the project, it has to unpack the barrel. So in this case, the garmin build commands fails as soon as you open the project, rather than after doing an optimized build.

You can, of course, write the optimized files anywhere you like. eg putting them in /tmp will avoid this issue...

Not sure there's much I can do about it in general though, so I'm going to close as a won't-fix.

**Comment by markw65** [comment]
> I think, PMC can do the same thing by unpacking barrels outside the project location.

My point is that you can already tell it where to put everything via `prettierMonkeyC.outputPath`
