### ISSUE TITLE
Incorrect typing for array of tuples

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#47]
```monkey-c
import Toybox.Lang;

function test() as Array<[Boolean, Number] or [Boolean]> {
    // Expected $.test to return Array<[Boolean, Number]> but got [[Boolean, Number], [Boolean]]
    return [[true, 0], [false]];
}
```

**Comment by markw65** [comment]
So this is actually intentional. It's not (in general) safe to return a tuple from a function expecting an array, and I've reported Garmin's behavior (which they have documented) as a bug.

Here's the basic problem:

```
var myTuple as [[Boolean, Number], [Boolean]] = [[false, true], [true]];

function bad() as Array<[Boolean, Number] or [Boolean]> {
  return myTuple; // Ok according to Garmin.
}

function really_bad() as Void {
  var myArray = bad();
  myArray[0] = [false]; // oops, now myTuple's first element is the wrong type
  myArray.add([true]); // oops, myTuple has too many elements
  // I could also remove elements from myTuple...
}
```

That said, *your* case is safe, because the value being returned has no other references, so there's nothing that cares if the returned tuple doesn't remain a tuple.

Note that there's a similar issue for object literal types getting passed where Dictionaries are expected (and for Dictionaries getting passed where object literal types are expected).

These are all ok when literals are involved (as in your example). So I may add a special case to handle that. But I don't really like that solution. Whether something passes the type checker should only depend on the types involved, not on the origin of the values.

The real issue here is that we need a `const` type. If your function could be marked as returning a `const Array` (or similarly for function arguments being marked as `const`), then all would be well.

**Comment by markw65** [comment]
Actually you're right. I originally did as I said, and prevented tuple->Array conversions, but it broke too much existing code, so I reported the bug, and changed my type checker to match Garmin's behavior (and then forgot that that's what I did, apparently!).

So this is a bug in the tuple -> Array conversion, I guess...
