### ISSUE TITLE
No warning about wrong argument type for Array.remove()

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#50]
```monkey-c
import Toybox.Lang;

function good(array as Array<Number>, value as Float) as Void {
    // "Argument 1 to $.Toybox.Lang.Array.add expected to be Number but got Float" as expected
    array.add(value);
}

function bad(array as Array<Number>, value as Float) as Void {
    // No warning about wrong argument type
    array.remove(value);
}
```

**Comment by markw65** [comment]
Hmm. This one's a bit philosophical.

Adding a `Float` to an array of `Number` is definitely an error.

Is it an error to try to find a `Float` in an array of `Number`? I could be keeping a list of "valid" things, and I use indexOf to determine if the thing I'm looking at is valid. I don't want to have to do a type check first, because if it's in the list, it's definitely the right type; and if it's not in the list, I don't care about it's type.

So what about removing an object? If it's the wrong type, it's not going to be in the array in the first place, so the remove is a no-op, and the type contract is not broken.

I agree, it could mean the user made an error, and is trying to remove the wrong thing - but in my opinion, it's better to allow this.

But I'm open to discussion (for example typescript completely disagrees with me - given a `Set<number>`, you can't lookup a `string` in it, and you can't delete a `string` from it - but frustrations arising from that behavior is actually the motivation here!).

**Comment by markw65** [comment]
I'm going to close this as not planned.
