### ISSUE TITLE
"Adding to a tuple would change its type" after assigning empty tuple to typed class variable

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#56]
```monkey-c
import Toybox.Lang;

class Test {
    private var array as Array<Number> = [];

    function test(x as Number) as Void {
        array = [];

        // Adding to a tuple would change its type
        array.add(x);
    }
}
```
I'd expect this message for `array` being local variable, but it is a class member, and `array = [];` assignment can't change its type as far as I understand.

**Comment by markw65** [comment]
> but it's not quite clear to me yet what we do want

Here's what I'm thinking. 

 - if the assignment is from a literal tuple, then we should widen the type to match the type of the variable. This still has some edge cases
   1. if the variable is declared as a union containing matching tuple types, the inferred type should be the union of those types (and should not include any matching Array components)
   1. otherwise, if the variable is declared as a union including some Array types, we should pick those components for which the initializer is a subtype.
- if it's not a literal tuple, we should keep the current behavior - because we explicitly want to prevent `array.add()`, for example

```
var x as Array<String> or Array<Number> = [];
var y as Array<String> or Array<Number> or [Number] = [];
function test1() as Array<Number> {
  x = [42];
  return x; // ok, only Array<Number> matched
}
function test2() as [Number] {
  y = [42];
  return y; // ok: since [Number] matched, we don't include Array<Number> too.
}
function test3(t as [Number]) as Array<Number> {
  x = t;
  return x; // error
}
```

But now, after writing that, I realized the correct fix for non-literal types is to generate an error on the assignment (at least, with extraReferenceTypeChecks set). I already do that when passing as an argument, but I missed it on assignment.

With that fixed, I think it just comes down to i) and ii)

**Comment by markw65** [comment]
> There's a small issue with its displaying in VS Code settings

Descriptions of settings can be plain `description`s or `markdownDescription`s. I'd used `description` by mistake, so the urls were ignored.

**Comment by markw65** [comment]
So after trying various things, it's become clear that this is a hard problem. If I type check member variables according to their declared type, then things that "should" be ok, are banned:

```
var array as Array<Number> or Array<String> = [];
function foo() as Void {
  array = [42];
  array[0] = 24; // illegal if we use the declared type, because array might be an array of String
}
```

Or the "reverse" of your example:

```
var array as Array<Number> or [Number] = [42];
function bar(a as Array<Number>) as Void {
  array = a;
  array.push(24); // illegal if we use the declared type, because array might hold a tuple
}
```

I think the solution is to track the array type ignoring the constraint (which is what I currently do), and issue warnings if the resulting type doesn't match the constraint. That still leaves a problem for what to do with the `extraReferenceTypeChecks` - but I think that only reporting them if they would apply to both the constraint type and the tracked type might be a good start.

In your case, we know that `array` holds an empty tuple, so `array.add(42)` turns that into `[Number]`, which is a subtype of `Array<Number>`, so no diagnostics are raised. `extraReferenceTypeChecks` apply to the tracked type, but not the constraint type, so we're good.

There still seem to be problem cases involving `extraReferenceTypeChecks`:

```
var array as Array<Number> or [String] = [];
function foo() as Void {
    array = [42];
    array.add(42);
}
```
When we get to the `array.add`, the tracked type is `[Number]`, and it's an error both for the tracked type, and the constraint type. If I extracted the components of the constraint type that match the tracked type, I would get `Array<Number>`, which seems to work for this example; so maybe I need to check all three types...

**Comment by markw65** [comment]
I just updated the extension with a fix for this. The analyzer seems to work reasonably well, but the optimizer can change code that would be ok, into code that warns, by introducing local variables, for example.
