### ISSUE TITLE
Minor: expected "Invalid assignment to array[0]", but no warnings for array[1]

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#57]
```monkey-c
import Toybox.Lang;

function test(array as Array<Number>, value1 as Number?, value2 as Number?) as Void {
    // "Invalid assignment to array[0]. Expected Number but got Null or Number" - OK
    array[0] = value1;
    // No warnings
    array[1] = value2;
}
```
I'm not sure, whether it is working as intended (maybe, there's no need to check other elements' assignments - something is wrong with this array anyway) or not.

**Comment by markw65** [comment]
This is as intended. When you assign `value1` to `array`, it warns because `array`'s type is `Array<Number>`. But it also updates `array`'s type to `Array<Number or Null>` - because that is what it actually contains. This update is important to prevent incorrect optimization, and also to give appropriate warnings later:

If you change it to:

```
import Toybox.Lang;
function foo(a as Array<Number>) as Void {}
function test(array as Array<Number>, value1 as Number?, value2 as Number?) as Void {
    foo(array); // ok
    array[0] = value1; // invalid (expecting Number, got Number or Null)
    foo(array); // invalid (expecting Array<Number>, got Array<Number or Null>)
    array[1] = value2; // ok
    array[2] = 42.0; // invalid (expecting Number or Null, got Float)
}
```
