### ISSUE TITLE
Undefined symbol for device personality class reference inside barrel

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#58]
It looks like barrels don't fully support references to device personality classes. 
`TestBarrel/resources/drawables.xml`:
```xml
<drawables>
    <bitmap id="BarrelBitmapWithDevicePersonality" filename="monkey.png" personality="system_size__menu_icon"/>
</drawables>
```

`barrelbuild` shows warning (not error) `Could not find personality style class 'system_size__menu_icon'.`, but `barrel` file is successfully created.

With something like
`TestProject/resources/menus/menu.xml`:
```xml
<menu2 id="MainMenu" title="Menu">
    <icon-menu-item id="item_0" label="@Strings.AppName" icon="@TestBarrel.Drawables.BarrelBitmapWithDevicePersonality"/>
    <menu-item id="item_1" label="@Strings.menu_label_1" />
    <menu-item id="item_2" label="@Strings.menu_label_2" />
</menu2>
```
in regular project everything works as expected, and project builds without errors or warnings.

PMC shows `Undefined symbol Rez.Styles.system_size__menu_icon` warning for `bitmap` declaration. Although it's true to some extent, I think, this warning is not very relevant, as it is possible to use barrels without ever calling `barrelbuild`.

Thank you very much for this project!

**Comment by markw65** [comment]
I think the solution here is to only have `TestProject` in your workspace (rather than a multi-project workspace including TestBarrel as well).

In that case, the barrel's source and resource files will still be checked, find refs and defs etc will still work across the project and barrel, but everything will happen in the context of TestProject, and it will find the correct personality reference.

Since I'm basically producing the exact same warning as MonkeyC for the Barrel project itself, this seems like the correct behavior?

**Comment by markw65** [comment]
> so this message is visible in barrel-only workspace too

Yes. And it's the exact same message that Garmin's compiler gives when compiling it in isolation. That was my point.

- if you open the Barrel project, you will get warnings based on that project in isolation
- if you only open the projects that use the barrel, you'll get warnings for the barrel based on the context it's used in.

> this warning is false positive from their point of view, as style will always be found during project build

Not if they try to build for a device that doesn't have a personality library...
