### ISSUE TITLE
Argument 1 to Dictionary.get expected to be Number<0> as Enum but got Number<0>

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#59]
```monkey-c
import Toybox.Lang;

enum Enum {
    ENUM,
}

const DICTIONARY = ({ ENUM => 1 }) as Dictionary<Enum, Number>;

function test1() as Void {
    test2();
}

function test2() as Object? {
    // Argument 1 to $.Toybox.Lang.Dictionary.get expected to be Number<0> as Enum but got Number<0>
    return DICTIONARY.get(ENUM);
}
```
This is shown only during build. Without `test1` function everything is OK.

**Comment by markw65** [comment]
Yet another place where a cached enum type was used after the enum was turned into a `Number`.

> Without test1 function everything is OK

This is because during the build, `test2` would be removed because it's unreferenced. By default, the optimizer runs a single pass removing unused functions. So in your example, it sees that `test2` is referenced, and keeps it, but `test1` is not, so it removes it. But then it stops. If you set `iterateOptimizer` it would keep going until it makes no further changes, and it would remove `test2` as well, and the error would not be reported.

For tests like this, you can work around it by applying `(:keep)` to `test2` (and then you don't need `test1` at all).

**Comment by markw65** [comment]
Done.

https://github.com/markw65/monkeyc-optimizer/wiki/Special-exclude-annotations
